spring:
    profiles:
        active: test1
---
server:
    port: 8282
spring:
    application:
        name: test
    profiles: test1
 
---
server:
    port: 8383
spring:
    application:
        name: test
    profiles: test2
