ceshi: abcafasdfasdf

---
server:
    port: 8585
spring:
    application:
        name: test
    profiles: test1
 
---
server:
    port: 8383
spring:
    application:
        name: test
    profiles: test2
